# 국가(대륙)별/상품군별 온라인 쇼핑 해외직접판매액

## K-Beauty는 성장하고 있을까? 해외 직접판매를 한다면 어느 국가로 판매전략을 세우면 좋을까?
* e : 추정치, p: 잠정치, - : 자료없음, ... : 미상자료, x : 비밀보호, ▽ : 시계열 불연 (단위 : 백만원)

# 필요 라이브러리 가져오기

In [1]:
# 라이브러리 로드
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# 시각화를 위한 폰트 설정
import os
if os.name == "posix" : 
    sns.set(font="AppleGothic")
    
elif os.name == "nt" :
    sns.set(font="Malgun Gothic")

In [3]:
# 러티나 설정을 해주면 글씨가 좀 더 선명하게 보임
# 폰트의 주변이 흐릿하게 보이는 것을 방지합니다.

%config InlineBackend.figure_format = 'nt'

ERROR:root:supported formats are: 'jpeg','retina','svg','png','jpg','png2x','pdf' not 'nt'

# 데이터 로드하기

In [4]:
df_raw = pd.read_csv("C:/Users/kim/jupyter/data analysis/국가_대륙_별_상품군별_온라인쇼핑_해외직접판매액_20201214235657.csv",
                     encoding = "cp949")
df_raw.shape

(450, 27)

In [5]:
# "국가(대륙)별" 데이터 빈도수 세기
df_raw["국가(대륙)별"].value_counts()

중국            45
아세안(ASEAN)    45
중남미           45
미국            45
합계            45
유럽연합(EU)      45
일본            45
대양주           45
기타            45
중동            45
Name: 국가(대륙)별, dtype: int64

In [6]:
# 미국 데이터만 따로 보기
df_raw[df_raw["국가(대륙)별"]=="미국"]

,국가(대륙)별,상품군별,판매유형별,2014 1/4,2014 2/4,2014 3/4,2014 4/4,2015 1/4,2015 2/4,2015 3/4,...,2017 3/4,2017 4/4,2018 1/4,2018 2/4,2018 3/4,2018 4/4,2019 1/4,2019 2/4,2019 3/4,2019 4/4
45,미국,합계,계,25773,22573,21288,26729,39945,26654,28647,...,41927,53209,42679,40207,37631,48978,40918,44861,55386,53848
46,미국,합계,면세점,-,-,-,-,-,-,-,...,9469,12177,5184,3603,2317,2079,2657,2951,1818,1481
47,미국,합계,면세점 이외,-,-,-,-,-,-,-,...,32458,41032,37495,36604,35314,46899,38261,41910,53568,52367
48,미국,컴퓨터 및 주변기기,계,2216,1666,1776,1675,1469,1393,2166,...,791,854,2033,1553,1784,1774,1298,1408,1653,1382
49,미국,컴퓨터 및 주변기기,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,1,0,0,0,0
50,미국,컴퓨터 및 주변기기,면세점 이외,-,-,-,-,-,-,-,...,791,854,2033,1553,1784,1773,1298,1408,1653,1382
51,미국,가전·전자·통신기기,계,2875,2758,2894,3527,4397,3589,2982,...,2575,2394,1737,1716,1723,1886,1845,1837,3166,1785
52,미국,가전·전자·통신기기,면세점,-,-,-,-,-,-,-,...,29,32,65,38,72,52,66,116,107,49
53,미국,가전·전자·통신기기,면세점 이외,-,-,-,-,-,-,-,...,2546,2362,1672,1678,1651,1834,1779,1721,3059,1736
54,미국,소프트웨어,계,47,57,49,128,182,113,163,...,37,125,175,251,172,269,88,156,118,338
55,미국,소프트웨어,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,0,0
56,미국,소프트웨어,면세점 이외,-,-,-,-,-,-,-,...,37,125,175,251,172,269,88,156,118,338
57,미국,서 적,계,962,720,934,1006,1074,837,993,...,1876,1856,2089,1790,2033,1977,2259,1563,2596,1720
58,미국,서 적,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,0,0
59,미국,서 적,면세점 이외,-,-,-,-,-,-,-,...,1876,1856,2089,1790,2033,1977,2259,1563,2596,1720
60,미국,사무·문구,계,25,10,14,18,568,17,32,...,30,79,58,55,85,83,198,72,83,101
61,미국,사무·문구,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,0,0
62,미국,사무·문구,면세점 이외,-,-,-,-,-,-,-,...,30,79,58,55,85,83,198,72,83,101
63,미국,음반·비디오·악기,계,787,720,722,821,849,781,827,...,2281,2647,2362,3014,3932,4550,3857,5191,5762,4786
64,미국,음반·비디오·악기,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,0,0
65,미국,음반·비디오·악기,면세점 이외,-,-,-,-,-,-,-,...,2281,2647,2362,3014,3932,4550,3857,5191,5762,4786
66,미국,의류 및 패션 관련상품,계,9810,7801,6404,9208,8602,6927,8055,...,11173,14483,11815,12169,10233,13658,12257,13571,13243,15964
67,미국,의류 및 패션 관련상품,면세점,-,-,-,-,-,-,-,...,148,129,116,154,134,118,110,115,95,91
68,미국,의류 및 패션 관련상품,면세점 이외,-,-,-,-,-,-,-,...,11025,14354,11699,12015,10099,13540,12147,13456,13148,15873
69,미국,스포츠·레저용품,계,573,539,475,491,541,527,481,...,874,1121,1181,1439,1200,1072,1152,1602,3149,858
70,미국,스포츠·레저용품,면세점,-,-,-,-,-,-,-,...,0,0,0,0,1,3,4,0,0,0
71,미국,스포츠·레저용품,면세점 이외,-,-,-,-,-,-,-,...,874,1121,1181,1439,1199,1069,1148,1602,3149,858
72,미국,화장품,계,3740,3713,3399,4595,11223,6176,7061,...,15997,22310,13909,11219,9717,15738,10817,11310,13999,13494
73,미국,화장품,면세점,-,-,-,-,-,-,-,...,9202,11913,4927,3311,2028,1780,2366,2647,1550,1271
74,미국,화장품,면세점 이외,-,-,-,-,-,-,-,...,6795,10397,8982,7908,7689,13958,8451,8663,12449,12223
75,미국,아동·유아용품,계,583,546,499,610,1099,603,619,...,592,722,766,793,730,1056,815,1153,1702,1928
76,미국,아동·유아용품,면세점,-,-,-,-,-,-,-,...,1,0,1,0,2,0,0,0,0,0
77,미국,아동·유아용품,면세점 이외,-,-,-,-,-,-,-,...,591,722,765,793,728,1056,815,1153,1702,1928
78,미국,음·식료품,계,381,415,405,673,577,628,631,...,417,265,277,311,239,278,336,313,602,424
79,미국,음·식료품,면세점,-,-,-,-,-,-,-,...,89,103,75,100,80,125,111,73,64,70
80,미국,음·식료품,면세점 이외,-,-,-,-,-,-,-,...,328,162,202,211,159,153,225,240,538,354
81,미국,농축수산물,계,94,98,111,160,189,192,193,...,0,2,1,0,0,33,2,2,7,2
82,미국,농축수산물,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,0,0
83,미국,농축수산물,면세점 이외,-,-,-,-,-,-,-,...,0,2,1,0,0,33,2,2,7,2
84,미국,생활용품 및 자동차용품,계,1931,1915,1815,1871,6605,2189,2207,...,2349,2276,2483,2357,2150,2159,2174,2410,3409,3713
85,미국,생활용품 및 자동차용품,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,2,0
86,미국,생활용품 및 자동차용품,면세점 이외,-,-,-,-,-,-,-,...,2349,2276,2483,2357,2150,2159,2174,2410,3407,3713
87,미국,기 타,계,1749,1615,1791,1946,2570,2682,2237,...,2935,4075,3793,3540,3633,4445,3820,4273,5897,7353
88,미국,기 타,면세점,-,-,-,-,-,-,-,...,0,0,0,0,0,0,0,0,0,0
89,미국,기 타,면세점 이외,-,-,-,-,-,-,-,...,2935,4075,3793,3540,3633,4445,3820,4273,5897,7353

# 분석과 시각화를 위한 tidy data 만들기

In [7]:
df_raw.columns

Index(['국가(대륙)별', '상품군별', '판매유형별', '2014 1/4', '2014 2/4', '2014 3/4',
       '2014 4/4', '2015 1/4', '2015 2/4', '2015 3/4', '2015 4/4', '2016 1/4',
       '2016 2/4', '2016 3/4', '2016 4/4', '2017 1/4', '2017 2/4', '2017 3/4',
       '2017 4/4', '2018 1/4', '2018 2/4', '2018 3/4', '2018 4/4', '2019 1/4',
       '2019 2/4', '2019 3/4', '2019 4/4'],
      dtype='object')

In [8]:
df = df_raw.melt(id_vars=["국가(대륙)별", "상품군별","판매유형별"],
                 var_name="기간",value_name = "백만원")
df.shape

(10800, 5)

In [9]:
df.info() # 데이터에 뭐가 들어있나 확인
# df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   국가(대륙)별  10800 non-null  object
 1   상품군별     10800 non-null  object
 2   판매유형별    10800 non-null  object
 3   기간       10800 non-null  object
 4   백만원      10800 non-null  object
dtypes: object(5)
memory usage: 422.0+ KB

# 데이터 전처리

## 기간에서 연도를 분리하기

In [10]:
# int("2014 1/4".split()[0]) # df["기간"]에서 연도만 추출

In [11]:
df["연도"] = df["기간"].map(lambda x : int(x.split()[0])) 
# lambda : 익명함수 x라는 변수 받음
# lambda가 받을 함수 = 기간  / 기간을 x로 받음 / x를 split한게 -> 연도 칼럼으로 들어감
df.head()

  국가(대륙)별        상품군별   판매유형별        기간     백만원    연도
0      합계          합계       계  2014 1/4  148272  2014
1      합계          합계     면세점  2014 1/4       -  2014
2      합계          합계  면세점 이외  2014 1/4       -  2014
3      합계  컴퓨터 및 주변기기       계  2014 1/4    4915  2014
4      합계  컴퓨터 및 주변기기     면세점  2014 1/4       -  2014

In [12]:
int("2014 1/4".split()[1].split("/")[0])

1

In [14]:
# 기간에서 분기만 분리하기

# df["분기"] = df["기간"].map(lambda x : int(x.split()[1].split("/")[0]))


df["분기"] = df["기간"].map(lambda x:int(x.split()[1].split("/")[0]))


df.head()

  국가(대륙)별        상품군별   판매유형별        기간     백만원    연도  분기
0      합계          합계       계  2014 1/4  148272  2014   1
1      합계          합계     면세점  2014 1/4       -  2014   1
2      합계          합계  면세점 이외  2014 1/4       -  2014   1
3      합계  컴퓨터 및 주변기기       계  2014 1/4    4915  2014   1
4      합계  컴퓨터 및 주변기기     면세점  2014 1/4       -  2014   1

In [ ]:
# 분기 컬럼 만들기

## 금액을 수치데이터로 표현하기 위해 데이터 타입 변경하기

In [29]:
# - 문자를 결측치로 변경하고 float 타입으로 변경하기

## 필요없는 데이터 제거하기

In [ ]:
# 합계 데이터는 따로 구할 수 있기 때문에 전체 데이터에서 제거

In [ ]:
# info로 정보보기어디서